---
#######################
#######################
## CI GitHub Actions ##
#######################
#######################
name: Continuous Integration

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Continuous Integration
    # Set the agent to run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout the code base
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      #################
      # Setup Node.js #
      #################
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

        ###################
        # Run npm scripts #
        ###################

      - name: Install dependencies
        run: npm ci

      - name: Smoke test building the project
        run: npm run build

      - name: Run unit tests
        run: npm run test
